from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class EndpointSeed:
    category: str
    path: str
    purpose: str
    params: dict[str, str] = field(default_factory=dict)
    update_frequency: str = "unknown"
    bot_value: str = "context"
    priority: int = 2
    collect_by_default: bool = True
    probe_by_default: bool = True


CATALOG: list[EndpointSeed] = [
    EndpointSeed(
        "market_status",
        "/api/marketStatus",
        "Official market/session state across NSE segments.",
        update_frequency="live/session",
        bot_value="avoid trading when market state is not normal",
        priority=1,
    ),
    EndpointSeed(
        "indices",
        "/api/allIndices",
        "All live index values, broad/sectoral/thematic index moves, and market status.",
        update_frequency="live",
        bot_value="breadth, sector rotation, risk-on/risk-off",
        priority=1,
    ),
    EndpointSeed(
        "indices",
        "/api/equity-stockIndices",
        "Index constituents with OHLC, last price, change, volume, value, FNO/SLB metadata.",
        {"index": "NIFTY 50"},
        update_frequency="live",
        bot_value="index heatmap, leaders/laggards, constituent pressure",
        priority=1,
    ),
    EndpointSeed(
        "indices",
        "/api/equity-stockIndices",
        "Bank Nifty constituents and banking-sector pressure.",
        {"index": "NIFTY BANK"},
        update_frequency="live",
        bot_value="banking rotation and index-driver map",
        priority=1,
    ),
    EndpointSeed(
        "indices",
        "/api/equity-stockIndices",
        "IT-sector constituents and sector pressure.",
        {"index": "NIFTY IT"},
        update_frequency="live",
        bot_value="sector heatmap for IT names and USD/US-tech sensitivity",
        priority=2,
    ),
    EndpointSeed(
        "indices",
        "/api/equity-stockIndices",
        "Auto-sector constituents and sector pressure.",
        {"index": "NIFTY AUTO"},
        update_frequency="live",
        bot_value="sector heatmap for auto names",
        priority=2,
    ),
    EndpointSeed(
        "indices",
        "/api/heatmap-index-catergory-list",
        "Heatmap index category list discovered from NSE heatmap assets.",
        update_frequency="live/static",
        bot_value="discovers broad, sectoral, thematic, strategy, and other heatmap groups",
        priority=1,
    ),
    EndpointSeed(
        "indices",
        "/api/heatmap-index",
        "Heatmap index-level data by category/type.",
        {"type": "CATEGORY_OR_INDEX_TYPE"},
        update_frequency="live",
        bot_value="official heatmap index pressure",
        priority=1,
        collect_by_default=False,
        probe_by_default=False,
    ),
    EndpointSeed(
        "indices",
        "/api/heatmap-symbols",
        "Heatmap constituent data by category/type.",
        {"type": "CATEGORY_OR_INDEX_TYPE"},
        update_frequency="live",
        bot_value="official symbol-level heatmap pressure",
        priority=1,
        collect_by_default=False,
        probe_by_default=False,
    ),
    EndpointSeed(
        "indices",
        "/api/chart-databyindex-dynamic",
        "Dynamic intraday chart data by index.",
        {"index": "NIFTY 50"},
        update_frequency="live",
        bot_value="official index chart path and regime confirmation",
        priority=2,
    ),
    EndpointSeed(
        "option_chain",
        "/api/option-chain-indices",
        "Index option chain with strike-wise CE/PE OI, change in OI, IV, volume, LTP.",
        {"symbol": "NIFTY"},
        update_frequency="live",
        bot_value="OI build-up, PCR, max pain candidates, gamma zones",
        priority=1,
    ),
    EndpointSeed(
        "option_chain",
        "/api/option-chain-indices",
        "Bank Nifty option chain.",
        {"symbol": "BANKNIFTY"},
        update_frequency="live",
        bot_value="banking index OI, IV, and strike pressure",
        priority=1,
    ),
    EndpointSeed(
        "option_chain",
        "/api/option-chain-equities",
        "Stock option chain for FNO symbols.",
        {"symbol": "RELIANCE"},
        update_frequency="live",
        bot_value="single-stock option interest and event pressure",
        priority=1,
    ),
    EndpointSeed(
        "quotes",
        "/api/quote-equity",
        "Official equity quote, metadata, trade info, delivery/trade data when present.",
        {"symbol": "RELIANCE"},
        update_frequency="live",
        bot_value="official quote sanity check and symbol metadata",
        priority=2,
    ),
    EndpointSeed(
        "quotes",
        "/api/quote-derivative",
        "Official derivative quote and contract metadata.",
        {"symbol": "NIFTY"},
        update_frequency="live",
        bot_value="official derivative contract sanity check",
        priority=2,
        collect_by_default=False,
    ),
    EndpointSeed(
        "pre_open",
        "/api/market-data-pre-open",
        "Opening auction data for pre-open market groups.",
        {"key": "NIFTY"},
        update_frequency="pre-open",
        bot_value="gap validation and auction imbalance context",
        priority=1,
    ),
    EndpointSeed(
        "live_analysis",
        "/api/live-analysis-variations",
        "Top gainers/losers and other live variation lists.",
        {"index": "gainers"},
        update_frequency="live",
        bot_value="momentum universe discovery",
        priority=2,
    ),
    EndpointSeed(
        "live_analysis",
        "/api/live-analysis-variations",
        "Top losers and negative momentum lists.",
        {"index": "losers"},
        update_frequency="live",
        bot_value="short-side or avoid-list momentum universe",
        priority=2,
    ),
    EndpointSeed(
        "live_analysis",
        "/api/live-analysis-most-active-securities",
        "Most active cash-market securities by value or volume.",
        {"index": "value"},
        update_frequency="live",
        bot_value="unusual cash-market participation",
        priority=2,
    ),
    EndpointSeed(
        "live_analysis",
        "/api/live-analysis-most-active-securities",
        "Most active cash-market securities by volume.",
        {"index": "volume"},
        update_frequency="live",
        bot_value="volume participation and unusual cash activity",
        priority=2,
    ),
    EndpointSeed(
        "live_analysis",
        "/api/live-analysis-most-active-contracts",
        "Most active derivatives contracts by volume/value.",
        {"index": "volume"},
        update_frequency="live",
        bot_value="FNO crowding and liquidity map",
        priority=2,
    ),
    EndpointSeed(
        "corporate",
        "/api/corporate-announcements",
        "Recent corporate announcements.",
        {"index": "equities"},
        update_frequency="near-live",
        bot_value="event-risk guardrail",
        priority=1,
    ),
    EndpointSeed(
        "corporate",
        "/api/corporates-board-meetings",
        "Board meeting calendar and filings.",
        {"index": "equities", "from_date": "DD-MM-YYYY", "to_date": "DD-MM-YYYY"},
        update_frequency="intraday/daily",
        bot_value="event-risk guardrail before entries",
        priority=1,
        collect_by_default=False,
        probe_by_default=False,
    ),
    EndpointSeed(
        "corporate",
        "/api/corporates-corporateActions",
        "Corporate actions such as dividend, split, bonus, rights, and buyback.",
        {"index": "equities", "from_date": "DD-MM-YYYY", "to_date": "DD-MM-YYYY"},
        update_frequency="intraday/daily",
        bot_value="avoid false gaps and corporate-action distortions",
        priority=1,
        collect_by_default=False,
        probe_by_default=False,
    ),
    EndpointSeed(
        "corporate",
        "/api/corporates-financial-results",
        "Financial results filings.",
        {"index": "equities"},
        update_frequency="as-filed",
        bot_value="earnings event-risk and result-day tags",
        priority=1,
        collect_by_default=False,
    ),
    EndpointSeed(
        "corporate",
        "/api/corporates-shareholdings-pattern",
        "Shareholding pattern filings.",
        {"index": "equities"},
        update_frequency="quarterly/as-filed",
        bot_value="ownership context for later bot memory",
        priority=3,
        collect_by_default=False,
    ),
    EndpointSeed(
        "market_activity",
        "/api/market-turnover",
        "Market turnover snapshot across NSE segments.",
        update_frequency="live/intraday",
        bot_value="liquidity and participation regime context",
        priority=2,
    ),
    EndpointSeed(
        "reference",
        "/api/smart-search/equity",
        "NSE equity smart search.",
        {"q": "RELIANCE"},
        update_frequency="static/live",
        bot_value="official symbol discovery and metadata lookup",
        priority=2,
        collect_by_default=False,
    ),
    EndpointSeed(
        "historical_reports",
        "/api/merged-daily-reports",
        "Merged daily report downloads by key.",
        {"key": "REPORT_KEY"},
        update_frequency="eod",
        bot_value="end-of-day dataset builder, not live entry trigger",
        priority=3,
        collect_by_default=False,
        probe_by_default=False,
    ),
    EndpointSeed(
        "exchange_communication",
        "/api/circulars",
        "Exchange circulars and member/listing/regulatory notices.",
        update_frequency="daily/intraday",
        bot_value="rule and surveillance change awareness",
        priority=3,
    ),
    EndpointSeed(
        "exchange_communication",
        "/api/holiday-master",
        "Trading and clearing holiday calendar.",
        {"type": "trading"},
        update_frequency="daily/static",
        bot_value="session calendar guardrail",
        priority=2,
        collect_by_default=False,
    ),
]


def iter_default_collect() -> list[EndpointSeed]:
    return [seed for seed in CATALOG if seed.collect_by_default]


def iter_default_probe() -> list[EndpointSeed]:
    return [seed for seed in CATALOG if seed.probe_by_default]
