from __future__ import annotations

from dataclasses import dataclass
from urllib.parse import urlencode
from urllib.parse import parse_qs, urlparse


@dataclass(frozen=True)
class EndpointProfile:
    category: str
    signal_type: str
    purpose: str
    update_frequency: str
    bot_value: str
    priority: int
    collect_by_default: bool = False


UNKNOWN_PROFILE = EndpointProfile(
    category="unknown",
    signal_type="candidate",
    purpose="Discovered NSE public API. Needs probing and response classification.",
    update_frequency="unknown",
    bot_value="catalog candidate until proven useful",
    priority=3,
)


FUNCTION_PROFILES: dict[str, EndpointProfile] = {
    "getGiftNifty": EndpointProfile(
        "global_context",
        "gift_nifty",
        "GIFT Nifty data from NSE modern API gateway.",
        "live/pre-open",
        "Overnight/pre-market India index context that broker ticks may not provide cleanly.",
        1,
    ),
    "getIndexData": EndpointProfile(
        "indices",
        "breadth",
        "Index data from NSE modern API gateway.",
        "live",
        "Broad/sector index regime and breadth context.",
        1,
    ),
    "getIndicesData": EndpointProfile(
        "indices",
        "constituent_pressure",
        "Index constituent/index data from NSE market-watch gateway.",
        "live",
        "Official leader/laggard and sector pressure map.",
        1,
    ),
    "getIndexList": EndpointProfile(
        "indices",
        "index_reference",
        "Index list from NSE market-watch gateway.",
        "static/live",
        "Discovers index names to drive heatmap and constituent collection.",
        1,
    ),
    "getIndexChart": EndpointProfile(
        "indices",
        "intraday_index_chart",
        "Index chart data from NSE market-watch gateway.",
        "live",
        "Official intraday index trend confirmation.",
        2,
    ),
    "getIndexGraph": EndpointProfile(
        "indices",
        "intraday_index_chart",
        "Index graph data from NSE dynamic gateway.",
        "live",
        "Official intraday index trend confirmation.",
        2,
    ),
    "getSymbolgraphData": EndpointProfile(
        "quotes",
        "symbol_chart",
        "Symbol graph data from NSE market-watch gateway.",
        "live",
        "Official symbol intraday path for sanity checks against broker candles.",
        2,
    ),
    "getMarketTurnoverSummary": EndpointProfile(
        "market_activity",
        "turnover",
        "Market turnover summary from NSE modern API gateway.",
        "live/intraday",
        "Liquidity and participation regime context.",
        2,
    ),
    "getBlockDealsData": EndpointProfile(
        "deals",
        "large_deal_flow",
        "Block deals data from NSE market-watch gateway.",
        "intraday/eod",
        "Large transaction context that can explain abnormal price/volume behavior.",
        2,
    ),
    "getETFData": EndpointProfile(
        "etf",
        "etf_activity",
        "ETF market-watch data from NSE gateway.",
        "live",
        "ETF liquidity, index-flow proxy, and sector participation context.",
        2,
    ),
    "getReitsInvitsData": EndpointProfile(
        "reits_invits",
        "yield_product_context",
        "REITs and INVITs data from NSE gateway.",
        "live/eod",
        "Yield-product liquidity context; usually not a core intraday equity trigger.",
        3,
    ),
    "getSGBData": EndpointProfile(
        "debt",
        "sgb_context",
        "Sovereign Gold Bond data from NSE gateway.",
        "live/eod",
        "Gold-linked market context; low urgency for equity intraday.",
        3,
    ),
    "getSmeData": EndpointProfile(
        "sme",
        "liquidity_context",
        "SME/Emerge data from NSE gateway.",
        "live/eod",
        "Flags low-liquidity names that should usually be blocked for automation.",
        3,
    ),
    "getT0Data": EndpointProfile(
        "market_structure",
        "settlement_context",
        "T+0 settlement data from NSE gateway.",
        "live/eod",
        "Market-structure eligibility and settlement context.",
        3,
    ),
    "getListingData": EndpointProfile(
        "primary_market",
        "listing_context",
        "Listing data from NSE gateway.",
        "as-filed/live",
        "Fresh listing context and new-symbol event risk.",
        2,
    ),
    "getNotificationList": EndpointProfile(
        "exchange_communication",
        "site_event",
        "Notification list from NSE CMS gateway.",
        "intraday",
        "Exchange notification awareness.",
        3,
    ),
    "getCurrentTime": EndpointProfile(
        "market_status",
        "exchange_time",
        "Current exchange/site time from NSE dynamic gateway.",
        "live",
        "Clock sanity check for session-aware collection.",
        2,
    ),
    "getNavbarData": EndpointProfile(
        "site_metadata",
        "navigation",
        "NSE navigation metadata.",
        "static",
        "Discovery support for finding more pages.",
        3,
    ),
    "getNotesData": EndpointProfile(
        "site_metadata",
        "document_notes",
        "NSE page notes/content metadata.",
        "static/as-requested",
        "Discovery and documentation support.",
        3,
    ),
}


EXACT_PROFILES: dict[str, EndpointProfile] = {
    "/api/marketStatus": EndpointProfile(
        "market_status",
        "risk_guard",
        "Official market/session state across NSE segments.",
        "live/session",
        "Stops the bot trading during closed, pre-open, special, or abnormal sessions.",
        1,
        True,
    ),
    "/api/allIndices": EndpointProfile(
        "indices",
        "breadth",
        "All live index values across broad, sectoral, strategy, thematic, and fixed-income groups.",
        "live",
        "Sector rotation, breadth pressure, index regime, and risk-on/risk-off map.",
        1,
        True,
    ),
    "/api/equity-stockIndices": EndpointProfile(
        "indices",
        "constituent_pressure",
        "Index constituent snapshot with price, change, volume, value, market cap, and near high/low fields.",
        "live",
        "Builds official heatmaps and detects leaders/laggards inside the index.",
        1,
        True,
    ),
    "/api/equity-stock-indices": EndpointProfile(
        "indices",
        "constituent_pressure",
        "Index constituent snapshot endpoint variant discovered from NSE bundles.",
        "live",
        "Official constituent pressure, leaders/laggards, and heatmap support.",
        1,
    ),
    "/api/equity-stockIndex": EndpointProfile(
        "indices",
        "constituent_pressure",
        "Index constituent snapshot endpoint variant discovered from NSE bundles.",
        "live",
        "Official constituent pressure and index-driver map.",
        1,
    ),
    "/api/equity-stockIndices-adu": EndpointProfile(
        "indices",
        "advance_decline",
        "Index advance/decline/up-down endpoint variant.",
        "live",
        "Breadth confirmation behind index moves.",
        1,
    ),
    "/api/chart-databyindex": EndpointProfile(
        "indices",
        "intraday_index_chart",
        "Index chart data by index name.",
        "live",
        "Official intraday index path for regime and trend confirmation.",
        2,
    ),
    "/api/chart-databyindex-dynamic": EndpointProfile(
        "indices",
        "intraday_index_chart",
        "Dynamic index chart data by index name.",
        "live",
        "Official intraday index path for regime and trend confirmation.",
        2,
    ),
    "/api/chart-databyindex-preopen-fo": EndpointProfile(
        "pre_open",
        "auction_imbalance",
        "Pre-open FNO chart data by index.",
        "pre-open",
        "Opening-auction context for derivative-heavy names.",
        1,
    ),
    "/api/chart-databyindex-spos-preopen": EndpointProfile(
        "pre_open",
        "auction_imbalance",
        "Special/pre-open chart data by index.",
        "pre-open",
        "Opening-auction context and special-session guardrail.",
        1,
    ),
    "/api/heatmap-index-catergory-list": EndpointProfile(
        "indices",
        "heatmap_metadata",
        "Heatmap index category list.",
        "live/static",
        "Discovers broad, sectoral, strategy, thematic, and other heatmap groups.",
        1,
    ),
    "/api/heatmap-index": EndpointProfile(
        "indices",
        "heatmap_index",
        "Heatmap index-level data by category/type.",
        "live",
        "Official index heatmap pressure without UI scraping.",
        1,
    ),
    "/api/heatmap-symbols": EndpointProfile(
        "indices",
        "heatmap_constituents",
        "Heatmap constituent symbols by type/index.",
        "live",
        "Official constituent heatmap and symbol pressure.",
        1,
    ),
    "/api/option-chain-indices": EndpointProfile(
        "option_chain",
        "option_flow",
        "Index option chain with strike-wise CE/PE OI, change in OI, IV, volume, and LTP.",
        "live",
        "OI build-up, PCR, strike magnets, expiry pressure, and option liquidity zones.",
        1,
        True,
    ),
    "/api/option-chain-equities": EndpointProfile(
        "option_chain",
        "option_flow",
        "Stock option chain for FNO symbols.",
        "live",
        "Single-stock derivative crowding, event pressure, and liquidity quality.",
        1,
        True,
    ),
    "/api/option-chain-v3": EndpointProfile(
        "option_chain",
        "option_flow",
        "Newer NSE option-chain endpoint variant with symbol and type parameters.",
        "live",
        "Unified option-chain discovery for indices/equities/derivative types.",
        1,
    ),
    "/api/option-chain-currency": EndpointProfile(
        "currency_derivatives",
        "option_flow",
        "Currency option chain.",
        "live",
        "USDINR and currency derivative pressure for macro-sensitive equity trades.",
        2,
    ),
    "/api/option-chain-com": EndpointProfile(
        "commodity_derivatives",
        "option_flow",
        "Commodity option chain.",
        "live",
        "Commodity derivative pressure for crude/metals-linked equity context.",
        3,
    ),
    "/api/option-chain-irf": EndpointProfile(
        "interest_rate_derivatives",
        "rates_option_flow",
        "Interest-rate futures/options chain.",
        "live",
        "Rates pressure context for banks, NBFCs, and bond-sensitive sectors.",
        3,
    ),
    "/api/option-chain-contract-info": EndpointProfile(
        "option_chain",
        "contract_reference",
        "Option-chain contract metadata for a symbol.",
        "live/static",
        "Expiry/contract availability reference for option-chain collection.",
        2,
    ),
    "/api/all-cd-symbols": EndpointProfile(
        "currency_derivatives",
        "symbol_reference",
        "Currency derivative symbol list.",
        "static/live",
        "Currency derivative universe for USDINR and macro-sensitive context.",
        3,
    ),
    "/api/irf-option-contracts": EndpointProfile(
        "interest_rate_derivatives",
        "contract_reference",
        "Interest-rate derivative option contracts.",
        "static/live",
        "Rates derivative contract universe.",
        3,
    ),
    "/api/quote-equity": EndpointProfile(
        "quotes",
        "official_quote",
        "Official equity quote, metadata, trade info, security info, and delivery fields when exposed.",
        "live",
        "Broker-data sanity check and exchange metadata for symbol decisions.",
        2,
        True,
    ),
    "/api/quote-derivative": EndpointProfile(
        "quotes",
        "official_derivative_quote",
        "Official derivative quote for futures/options contracts.",
        "live",
        "Contract sanity check, expiry/strike metadata, and official derivative snapshot.",
        2,
    ),
    "/api/master-quote": EndpointProfile(
        "reference",
        "quote_master",
        "Master quote/reference endpoint used by quote and option-chain pages.",
        "static/live",
        "Instrument lookup and official metadata support.",
        2,
    ),
    "/api/quotes-commodity-derivatives-master": EndpointProfile(
        "commodity_derivatives",
        "contract_reference",
        "Commodity derivatives master quote/reference endpoint.",
        "static/live",
        "Commodity derivative universe and contract metadata.",
        3,
    ),
    "/api/market-data-pre-open": EndpointProfile(
        "pre_open",
        "auction_imbalance",
        "Pre-open auction data for indices, equities, SME, and related groups.",
        "pre-open",
        "Gap validation, auction imbalance, and avoid-chasing filter.",
        1,
        True,
    ),
    "/api/live-analysis-variations": EndpointProfile(
        "live_analysis",
        "momentum_universe",
        "Live gainers/losers and variation lists.",
        "live",
        "Momentum universe, exhaustion candidates, and relative-strength watchlist.",
        2,
        True,
    ),
    "/api/live-analysis-most-active-securities": EndpointProfile(
        "live_analysis",
        "cash_activity",
        "Most active cash-market securities by traded value or volume.",
        "live",
        "Finds where real cash-market participation is concentrated.",
        2,
        True,
    ),
    "/api/live-analysis-most-active-contracts": EndpointProfile(
        "live_analysis",
        "derivative_activity",
        "Most active derivative contracts by traded value or volume.",
        "live",
        "Finds crowded/liquid FNO contracts and unusual derivatives attention.",
        2,
        True,
    ),
    "/api/live-analysis-most-active-etf": EndpointProfile(
        "etf",
        "etf_activity",
        "Most active ETFs by value or volume.",
        "live",
        "ETF liquidity and sector/index participation context.",
        2,
    ),
    "/api/live-analysis-most-active-etf-csv": EndpointProfile(
        "etf",
        "etf_activity_download",
        "CSV download for most active ETFs.",
        "live",
        "Offline ETF activity snapshot.",
        3,
    ),
    "/api/live-analysis-volume-gainers": EndpointProfile(
        "live_analysis",
        "volume_spike",
        "Live volume gainers.",
        "live",
        "Unusual volume universe for intraday anomaly discovery.",
        1,
    ),
    "/api/liveEquity-derivatives": EndpointProfile(
        "derivatives",
        "fno_watch",
        "Live equity derivatives watch data.",
        "live",
        "FNO price/OI/liquidity context for single-stock intraday filters.",
        1,
    ),
    "/api/refrates": EndpointProfile(
        "currency_derivatives",
        "reference_rates",
        "Reference rates endpoint used by derivatives pages.",
        "intraday/daily",
        "FX/rates context for macro-sensitive sectors.",
        3,
    ),
    "/api/corporate-announcements": EndpointProfile(
        "corporate",
        "event_risk",
        "Recent company announcements filed with NSE.",
        "near-live",
        "Blocks or downgrades trades when fresh exchange filings can move price.",
        1,
        True,
    ),
    "/api/corporates-board-meetings": EndpointProfile(
        "corporate",
        "event_calendar",
        "Board meeting calendar and announcements.",
        "intraday/daily",
        "Avoids entering before event-risk windows.",
        1,
    ),
    "/api/corporates-corporateActions": EndpointProfile(
        "corporate",
        "corporate_action",
        "Dividends, splits, bonuses, rights, buybacks, and other actions.",
        "intraday/daily",
        "Adjusts or blocks trades around corporate-action distortions.",
        1,
    ),
    "/api/corporates-financial-results": EndpointProfile(
        "corporate",
        "results_event",
        "Financial results filings.",
        "intraday/daily",
        "Earnings-day risk and post-result universe tagging.",
        1,
    ),
    "/api/corporates-shareholdings-pattern": EndpointProfile(
        "corporate",
        "ownership",
        "Shareholding pattern filings.",
        "quarterly/as-filed",
        "Ownership context unavailable from broker ticks.",
        3,
    ),
    "/api/circulars": EndpointProfile(
        "exchange_communication",
        "rule_event",
        "Exchange circulars and notices.",
        "intraday/daily",
        "Detects rule, margin, market-structure, and surveillance changes.",
        3,
        True,
    ),
    "/api/latest-circular": EndpointProfile(
        "exchange_communication",
        "rule_event",
        "Latest exchange circulars and notices.",
        "intraday/daily",
        "Early rule, margin, and market-structure awareness.",
        3,
    ),
    "/api/holiday-master": EndpointProfile(
        "exchange_communication",
        "calendar_guard",
        "Trading and clearing holidays.",
        "daily/static",
        "Prevents bot schedules from assuming a normal session.",
        2,
    ),
    "/api/market-turnover": EndpointProfile(
        "market_activity",
        "turnover",
        "Market turnover snapshot across segments.",
        "live/intraday",
        "Participation and liquidity regime context.",
        2,
    ),
    "/api/market-turnover-popup": EndpointProfile(
        "market_activity",
        "turnover_detail",
        "Detailed market turnover popup data.",
        "live/intraday",
        "Segment-level liquidity context.",
        3,
    ),
    "/api/smart-search/": EndpointProfile(
        "reference",
        "symbol_search",
        "NSE smart search base endpoint.",
        "static/live",
        "Symbol discovery and symbol-to-instrument mapping support.",
        2,
    ),
    "/api/smart-search/equity": EndpointProfile(
        "reference",
        "symbol_search",
        "Equity smart search.",
        "static/live",
        "Symbol discovery and exchange metadata lookup.",
        2,
    ),
    "/api/smart-search/eqEtf": EndpointProfile(
        "reference",
        "symbol_search",
        "Equity and ETF smart search.",
        "static/live",
        "Symbol discovery for equities and ETFs.",
        2,
    ),
    "/api/quick-links-corporate": EndpointProfile(
        "corporate",
        "issuer_reference",
        "Corporate quick links for a symbol.",
        "static/as-filed",
        "Finds official issuer pages and filing routes for a symbol.",
        3,
    ),
    "/api/download_xbrl": EndpointProfile(
        "corporate",
        "xbrl_filing",
        "XBRL filing download endpoint.",
        "as-filed",
        "Raw official filing payload for deeper event-risk parsing.",
        3,
    ),
    "/api/xbrl/": EndpointProfile(
        "corporate",
        "xbrl_filing",
        "XBRL filing endpoint namespace.",
        "as-filed",
        "Official structured filings for research and event parsing.",
        3,
    ),
    "/api/download-drhp-file": EndpointProfile(
        "primary_market",
        "ipo_document",
        "DRHP/RHP document download endpoint.",
        "as-filed",
        "IPO and primary-market event context.",
        3,
    ),
    "/api/corp-bond-details": EndpointProfile(
        "debt",
        "bond_reference",
        "Corporate bond details by ISIN.",
        "intraday/eod",
        "Rates, credit, and liquidity context outside broker feeds.",
        3,
    ),
    "/api/negotiated-trade-details": EndpointProfile(
        "debt",
        "negotiated_trade",
        "Negotiated trade details by ISIN.",
        "intraday/eod",
        "Large debt-market trade context and liquidity signals.",
        3,
    ),
    "/api/merged-daily-reports": EndpointProfile(
        "historical_reports",
        "daily_report",
        "Merged daily report downloads by report key.",
        "eod",
        "Offline research and end-of-day validation.",
        3,
    ),
    "/api/reports": EndpointProfile(
        "historical_reports",
        "report_download",
        "Report archive/download endpoint.",
        "eod/as-requested",
        "Offline research, bhavcopy-style reports, and validations.",
        3,
    ),
    "/api/syncDailyReport": EndpointProfile(
        "historical_reports",
        "daily_report_download",
        "Daily report sync/download endpoint.",
        "eod",
        "End-of-day dataset builder.",
        3,
    ),
    "/api/zipem": EndpointProfile(
        "historical_reports",
        "bulk_download",
        "Bulk zip download endpoint for exchange files.",
        "eod/as-requested",
        "Historical/archive dataset assembly.",
        3,
    ),
    "/api/eventnotification": EndpointProfile(
        "exchange_communication",
        "site_event",
        "Exchange/site event notifications.",
        "intraday",
        "Exchange event awareness and operational notices.",
        3,
    ),
    "/api/contingency-drill-calender": EndpointProfile(
        "exchange_communication",
        "operational_calendar",
        "Contingency drill calendar.",
        "daily/static",
        "Operational-session awareness.",
        3,
    ),
    "/api/contingency-drill-calender-json": EndpointProfile(
        "exchange_communication",
        "operational_calendar",
        "Contingency drill calendar JSON.",
        "daily/static",
        "Operational-session awareness.",
        3,
    ),
    "/api/regulatorymodulestatus": EndpointProfile(
        "regulatory",
        "module_status",
        "Regulatory module status.",
        "intraday",
        "Operational/regulatory availability context.",
        3,
    ),
    "/api/commonnse": EndpointProfile(
        "site_metadata",
        "site_config",
        "Common NSE site metadata endpoint.",
        "static/intraday",
        "Useful for discovery, usually not a trading signal.",
        3,
    ),
    "/api/homegraphtype": EndpointProfile(
        "site_metadata",
        "home_chart_config",
        "Homepage graph type/config endpoint.",
        "static/intraday",
        "Discovery support, usually not a trading signal.",
        3,
    ),
    "/api/getNotes20": EndpointProfile(
        "site_metadata",
        "document_notes",
        "Document notes helper endpoint.",
        "static/as-requested",
        "Discovery/support only.",
        3,
    ),
    "/api/recaptcha-client-secret": EndpointProfile(
        "site_plumbing",
        "captcha",
        "Captcha/client security helper.",
        "runtime",
        "Not useful for trading data; keep out of gold collection.",
        3,
    ),
    "/api/NextApi/apiClient": EndpointProfile(
        "next_api_gateway",
        "gateway",
        "NSE NextApi generic API client wrapper. Classify deeper by functionName parameter after probing.",
        "varies",
        "Discovery gateway; useful for finding modern page-backed APIs, not direct gold by itself.",
        3,
    ),
    "/api/NextApi/apiClient/marketWatchApi": EndpointProfile(
        "next_api_gateway",
        "market_watch_gateway",
        "NSE NextApi market-watch wrapper. FunctionName controls the actual dataset.",
        "live/varies",
        "Important discovery gateway for live market-watch pages.",
        2,
    ),
    "/api/NextApi/apiStatic": EndpointProfile(
        "next_api_gateway",
        "static_gateway",
        "NSE NextApi static-content wrapper.",
        "static/as-requested",
        "Discovery and static reference gateway.",
        3,
    ),
    "/api/NextApi/cmsHandler": EndpointProfile(
        "next_api_gateway",
        "cms_gateway",
        "NSE CMS wrapper endpoint.",
        "static/as-requested",
        "Site content discovery, normally not trading gold.",
        3,
    ),
    "/api/NextApi/dynamicApi": EndpointProfile(
        "next_api_gateway",
        "dynamic_gateway",
        "NSE dynamic API wrapper. FunctionName controls the actual dataset.",
        "varies",
        "Discovery gateway for newer dynamic NSE pages.",
        2,
    ),
    "/api/NextApi/globalSearch": EndpointProfile(
        "reference",
        "global_search",
        "NSE global search endpoint.",
        "static/live",
        "Symbol/page discovery and reference lookup.",
        2,
    ),
}


PATTERN_PROFILES: list[tuple[tuple[str, ...], EndpointProfile]] = [
    (
        ("surveillance", "asm", "gsm", "price-band", "priceband", "band-hitter"),
        EndpointProfile(
            "surveillance",
            "risk_guard",
            "Surveillance, price-band, circuit, or trade-control data.",
            "intraday/daily",
            "Hard risk filter for symbols that can trap intraday entries.",
            1,
        ),
    ),
    (
        ("bulk", "block", "large-deal"),
        EndpointProfile(
            "deals",
            "large_deal_flow",
            "Bulk deals, block deals, or large-deal market data.",
            "intraday/eod",
            "Identifies unusual institutional-style prints unavailable in broker candles.",
            2,
        ),
    ),
    (
        ("52", "high-low", "week"),
        EndpointProfile(
            "live_analysis",
            "breakout_universe",
            "52-week high/low or breakout-style market list.",
            "live/eod",
            "Breakout watchlist and trend-extension filter.",
            2,
        ),
    ),
    (
        ("oi", "open-interest", "most-active-underlying"),
        EndpointProfile(
            "derivatives",
            "option_flow",
            "Open interest, most-active underlying, or derivatives participation data.",
            "live",
            "Derivative pressure map for FNO symbols and indices.",
            1,
        ),
    ),
    (
        ("etf",),
        EndpointProfile(
            "etf",
            "etf_context",
            "ETF market data or reference endpoint.",
            "live/eod",
            "ETF liquidity, sector proxy, and index-flow context.",
            2,
        ),
    ),
    (
        ("currency", "cd-", "usd", "inr"),
        EndpointProfile(
            "currency_derivatives",
            "macro_fx_context",
            "Currency derivative or FX reference endpoint.",
            "live/intraday",
            "USDINR and FX context for IT, pharma, oil, metals, and import/export names.",
            3,
        ),
    ),
    (
        ("commodity", "com-"),
        EndpointProfile(
            "commodity_derivatives",
            "macro_commodity_context",
            "Commodity derivative endpoint.",
            "live/intraday",
            "Crude/metals/agri context for sector-sensitive equities.",
            3,
        ),
    ),
    (
        ("irf", "interest-rate", "refrates"),
        EndpointProfile(
            "interest_rate_derivatives",
            "rates_context",
            "Interest-rate derivative or reference-rate endpoint.",
            "live/intraday",
            "Rates context for financials and debt-sensitive sectors.",
            3,
        ),
    ),
    (
        ("pre-open", "preopen"),
        EXACT_PROFILES["/api/market-data-pre-open"],
    ),
    (
        ("sme", "emerge"),
        EndpointProfile(
            "sme",
            "liquidity_context",
            "SME/Emerge market data.",
            "live/eod",
            "Flags low-liquidity names that should usually be blocked for automation.",
            3,
        ),
    ),
    (
        ("slb", "lending", "borrowing"),
        EndpointProfile(
            "slb",
            "borrow_context",
            "Securities lending and borrowing data.",
            "intraday/eod",
            "Shorting/borrow context and unusual lending activity.",
            3,
        ),
    ),
    (
        ("historical", "archives", "bhavcopy", "daily-reports", "reports"),
        EndpointProfile(
            "historical_reports",
            "research_dataset",
            "Historical or daily report download APIs.",
            "eod",
            "Offline research and validation, not live execution.",
            3,
        ),
    ),
    (
        ("debt", "bond", "gsec", "tri-party", "repo", "rfq"),
        EndpointProfile(
            "debt",
            "macro_liquidity",
            "Debt, bond, RFQ, repo, or fixed-income data.",
            "intraday/eod",
            "Macro liquidity and rates context, not a direct equity entry trigger.",
            3,
        ),
    ),
    (
        ("ipo", "public-issue", "ofs", "rights", "reits", "invits"),
        EndpointProfile(
            "primary_market",
            "event_risk",
            "Primary-market issue, OFS, rights, REIT, INVIT, or tender-offer data.",
            "as-filed",
            "Event-risk calendar and universe exclusions.",
            3,
        ),
    ),
]


def profile_endpoint(url_or_path: str) -> EndpointProfile:
    parsed = urlparse(url_or_path)
    path = parsed.path or url_or_path.split("?", 1)[0]
    params = {key: values[-1] for key, values in parse_qs(parsed.query, keep_blank_values=True).items()}
    if params.get("functionName") in FUNCTION_PROFILES:
        return FUNCTION_PROFILES[params["functionName"]]
    if path in EXACT_PROFILES:
        return EXACT_PROFILES[path]

    haystack = path.lower()
    for tokens, profile in PATTERN_PROFILES:
        if any(token in haystack for token in tokens):
            return profile
    return UNKNOWN_PROFILE


def profile_endpoint_from_parts(path: str, params: dict[str, str]) -> EndpointProfile:
    if params.get("functionName") in FUNCTION_PROFILES:
        return FUNCTION_PROFILES[params["functionName"]]
    query = urlencode(params)
    return profile_endpoint(f"{path}?{query}" if query else path)


def endpoint_path(url_or_path: str) -> str:
    parsed = urlparse(url_or_path)
    return parsed.path or url_or_path.split("?", 1)[0]


def endpoint_params(url_or_path: str) -> dict[str, str]:
    parsed = urlparse(url_or_path)
    return {key: values[-1] for key, values in parse_qs(parsed.query, keep_blank_values=True).items()}


def endpoint_param_names(url_or_path: str) -> list[str]:
    return sorted(endpoint_params(url_or_path).keys())
